package io.github.zenhelix.dependanger.features.transitive

import io.github.zenhelix.dependanger.effective.spi.StrictOnlyPresetContributor

public class TransitiveResolverPresetContributor : StrictOnlyPresetContributor(TransitiveResolverProcessor.PROCESSOR_ID)
