package io.github.zenhelix.dependanger.features.analysis

import io.github.zenhelix.dependanger.effective.spi.StrictOnlyPresetContributor

public class CompatibilityCheckPresetContributor : StrictOnlyPresetContributor(CompatibilityCheckProcessor.PROCESSOR_ID)
