package io.github.zenhelix.dependanger.generators.toml

import io.github.zenhelix.dependanger.core.model.DeprecationInfo
import io.github.zenhelix.dependanger.core.model.Diagnostics
import io.github.zenhelix.dependanger.effective.model.EffectiveBundle
import io.github.zenhelix.dependanger.effective.model.EffectiveLibrary
import io.github.zenhelix.dependanger.effective.model.EffectiveMetadata
import io.github.zenhelix.dependanger.effective.model.EffectivePlugin
import io.github.zenhelix.dependanger.effective.model.ResolvedVersion
import io.github.zenhelix.dependanger.effective.model.VersionSource
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Path
import kotlin.io.path.readText

class TomlGeneratorTest {

    private fun emptyMetadata(
        versions: Map<String, ResolvedVersion> = emptyMap(),
        libraries: Map<String, EffectiveLibrary> = emptyMap(),
        plugins: Map<String, EffectivePlugin> = emptyMap(),
        bundles: Map<String, EffectiveBundle> = emptyMap(),
    ): EffectiveMetadata = EffectiveMetadata(
        schemaVersion = "1.0",
        distribution = null,
        versions = versions,
        libraries = libraries,
        plugins = plugins,
        bundles = bundles,
        diagnostics = Diagnostics.EMPTY,
        processingInfo = null,
    )

    private fun version(alias: String, value: String): ResolvedVersion =
        ResolvedVersion(alias = alias, value = value, source = VersionSource.DECLARED, originalRef = null)

    private fun library(
        alias: String,
        group: String,
        artifact: String,
        version: ResolvedVersion? = null,
        isDeprecated: Boolean = false,
        deprecation: DeprecationInfo? = null,
        isPlatform: Boolean = false,
    ): EffectiveLibrary = EffectiveLibrary(
        alias = alias,
        group = group,
        artifact = artifact,
        version = version,
        description = null,
        tags = emptySet(),
        requires = null,
        isDeprecated = isDeprecated,
        deprecation = deprecation,
        license = null,
        constraints = emptyList(),
        isPlatform = isPlatform,
    )

    private fun plugin(alias: String, id: String, version: ResolvedVersion? = null): EffectivePlugin =
        EffectivePlugin(alias = alias, id = id, version = version)

    private fun bundle(alias: String, libraries: List<String>): EffectiveBundle =
        EffectiveBundle(alias = alias, libraries = libraries)

    @Nested
    inner class EmptyMetadata {
        @Test
        fun `empty metadata with comments produces header only`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val result = generator.generate(emptyMetadata())

            assertThat(result).isEqualTo("# Generated by Dependanger (toml-version-catalog)\n")
        }

        @Test
        fun `empty metadata without comments produces single newline`() {
            val config = TomlConfig.DEFAULT.copy(includeComments = false)
            val generator = TomlGenerator(config)
            val result = generator.generate(emptyMetadata())

            assertThat(result).isEqualTo("\n")
        }
    }

    @Nested
    inner class VersionsSection {
        @Test
        fun `versions section generated correctly`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("kotlin", "2.1.20")
            val result = generator.generate(emptyMetadata(versions = mapOf("kotlin" to v)))

            assertThat(result).contains("[versions]")
            assertThat(result).contains("kotlin = \"2.1.20\"")
        }

        @Test
        fun `versions sorted alphabetically when sortSections is true`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val versions = linkedMapOf(
                "spring-boot" to version("spring-boot", "3.4.0"),
                "kotlin" to version("kotlin", "2.1.20"),
                "assertj" to version("assertj", "3.27.3"),
            )
            val result = generator.generate(emptyMetadata(versions = versions))

            val lines = result.lines()
            val versionLines = lines.filter { it.contains(" = \"") && !it.startsWith("[") && !it.startsWith("#") }
            assertThat(versionLines).containsExactly(
                "assertj = \"3.27.3\"",
                "kotlin = \"2.1.20\"",
                "spring-boot = \"3.4.0\"",
            )
        }

        @Test
        fun `versions not sorted when sortSections is false`() {
            val config = TomlConfig.DEFAULT.copy(includeComments = false, sortSections = false)
            val generator = TomlGenerator(config)
            val versions = linkedMapOf(
                "spring-boot" to version("spring-boot", "3.4.0"),
                "kotlin" to version("kotlin", "2.1.20"),
            )
            val result = generator.generate(emptyMetadata(versions = versions))
            val versionIndex1 = result.indexOf("spring-boot")
            val versionIndex2 = result.indexOf("kotlin")
            assertThat(versionIndex1).isLessThan(versionIndex2)
        }
    }

    @Nested
    inner class LibrariesSection {
        @Test
        fun `library with version ref`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("kotlin", "2.1.20")
            val lib = library("kotlin-stdlib", "org.jetbrains.kotlin", "kotlin-stdlib", version = v)
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("kotlin" to v),
                    libraries = mapOf("kotlin-stdlib" to lib),
                )
            )

            assertThat(result).contains("[libraries]")
            assertThat(result).contains("kotlin-stdlib = { group = \"org.jetbrains.kotlin\", name = \"kotlin-stdlib\", version.ref = \"kotlin\" }")
        }

        @Test
        fun `library with inline version`() {
            val config = TomlConfig.DEFAULT.copy(includeComments = false, useInlineVersions = true)
            val generator = TomlGenerator(config)
            val v = version("kotlin", "2.1.20")
            val lib = library("kotlin-stdlib", "org.jetbrains.kotlin", "kotlin-stdlib", version = v)
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("kotlin" to v),
                    libraries = mapOf("kotlin-stdlib" to lib),
                )
            )

            assertThat(result).contains("kotlin-stdlib = { group = \"org.jetbrains.kotlin\", name = \"kotlin-stdlib\", version = \"2.1.20\" }")
        }

        @Test
        fun `library without version`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val lib = library("managed-dep", "com.example", "managed")
            val result = generator.generate(emptyMetadata(libraries = mapOf("managed-dep" to lib)))

            assertThat(result).contains("managed-dep = { group = \"com.example\", name = \"managed\" }")
        }

        @Test
        fun `library version ref fallback to inline when alias not in versions`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("not-in-versions", "1.0.0")
            val lib = library("some-lib", "com.example", "some-lib", version = v)
            val result = generator.generate(
                emptyMetadata(
                    libraries = mapOf("some-lib" to lib),
                )
            )

            assertThat(result).contains("some-lib = { group = \"com.example\", name = \"some-lib\", version = \"1.0.0\" }")
            assertThat(result).doesNotContain("version.ref")
        }

        @Test
        fun `platform library generated as normal entry`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("spring-boot", "3.4.0")
            val lib = library("spring-boot-bom", "org.springframework.boot", "spring-boot-dependencies", version = v, isPlatform = true)
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("spring-boot" to v),
                    libraries = mapOf("spring-boot-bom" to lib),
                )
            )

            assertThat(result).contains("spring-boot-bom = { group = \"org.springframework.boot\", name = \"spring-boot-dependencies\", version.ref = \"spring-boot\" }")
        }
    }

    @Nested
    inner class DeprecationComments {
        @Test
        fun `deprecated library with full info`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("spring-boot", "3.4.0")
            val lib = library(
                alias = "spring-boot-starter",
                group = "org.springframework.boot",
                artifact = "spring-boot-starter",
                version = v,
                isDeprecated = true,
                deprecation = DeprecationInfo(
                    message = "Legacy starter",
                    replacedBy = "spring-boot-starter-web",
                    since = "3.0",
                    removalVersion = "4.0",
                ),
            )
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("spring-boot" to v),
                    libraries = mapOf("spring-boot-starter" to lib),
                )
            )

            assertThat(result).contains("# DEPRECATED: Legacy starter. Use spring-boot-starter-web instead. Removal: 4.0.")
        }

        @Test
        fun `deprecated library with partial info - no deprecation object`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val lib = library(
                alias = "old-lib",
                group = "com.example",
                artifact = "old-lib",
                isDeprecated = true,
                deprecation = null,
            )
            val result = generator.generate(emptyMetadata(libraries = mapOf("old-lib" to lib)))

            assertThat(result).contains("# DEPRECATED.")
        }

        @Test
        fun `deprecated library with only message`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val lib = library(
                alias = "old-lib",
                group = "com.example",
                artifact = "old-lib",
                isDeprecated = true,
                deprecation = DeprecationInfo(message = "No longer maintained", replacedBy = null, since = null, removalVersion = null),
            )
            val result = generator.generate(emptyMetadata(libraries = mapOf("old-lib" to lib)))

            assertThat(result).contains("# DEPRECATED: No longer maintained.")
        }

        @Test
        fun `deprecated library with only replacedBy`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val lib = library(
                alias = "old-lib",
                group = "com.example",
                artifact = "old-lib",
                isDeprecated = true,
                deprecation = DeprecationInfo(message = null, replacedBy = "new-lib", since = null, removalVersion = null),
            )
            val result = generator.generate(emptyMetadata(libraries = mapOf("old-lib" to lib)))

            assertThat(result).contains("# DEPRECATED. Use new-lib instead.")
        }

        @Test
        fun `deprecation comments disabled`() {
            val config = TomlConfig.DEFAULT.copy(includeComments = false, includeDeprecationComments = false)
            val generator = TomlGenerator(config)
            val lib = library(
                alias = "old-lib",
                group = "com.example",
                artifact = "old-lib",
                isDeprecated = true,
                deprecation = DeprecationInfo(message = "Deprecated", replacedBy = "new-lib", since = null, removalVersion = "2.0"),
            )
            val result = generator.generate(emptyMetadata(libraries = mapOf("old-lib" to lib)))

            assertThat(result).doesNotContain("# DEPRECATED")
            assertThat(result).contains("old-lib = { group = \"com.example\", name = \"old-lib\" }")
        }
    }

    @Nested
    inner class BundlesSection {
        @Test
        fun `bundles section generated correctly`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val b = bundle("kotlin", listOf("kotlin-stdlib", "kotlin-reflect"))
            val result = generator.generate(emptyMetadata(bundles = mapOf("kotlin" to b)))

            assertThat(result).contains("[bundles]")
            assertThat(result).contains("kotlin = [\"kotlin-stdlib\", \"kotlin-reflect\"]")
        }

        @Test
        fun `empty bundle`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val b = bundle("empty", emptyList())
            val result = generator.generate(emptyMetadata(bundles = mapOf("empty" to b)))

            assertThat(result).contains("empty = []")
        }
    }

    @Nested
    inner class PluginsSection {
        @Test
        fun `plugin with version ref`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("kotlin", "2.1.20")
            val p = plugin("kotlin-jvm", "org.jetbrains.kotlin.jvm", version = v)
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("kotlin" to v),
                    plugins = mapOf("kotlin-jvm" to p),
                )
            )

            assertThat(result).contains("[plugins]")
            assertThat(result).contains("kotlin-jvm = { id = \"org.jetbrains.kotlin.jvm\", version.ref = \"kotlin\" }")
        }

        @Test
        fun `plugin with inline version`() {
            val config = TomlConfig.DEFAULT.copy(includeComments = false, useInlineVersions = true)
            val generator = TomlGenerator(config)
            val v = version("kotlin", "2.1.20")
            val p = plugin("kotlin-jvm", "org.jetbrains.kotlin.jvm", version = v)
            val result = generator.generate(
                emptyMetadata(
                    versions = mapOf("kotlin" to v),
                    plugins = mapOf("kotlin-jvm" to p),
                )
            )

            assertThat(result).contains("kotlin-jvm = { id = \"org.jetbrains.kotlin.jvm\", version = \"2.1.20\" }")
        }

        @Test
        fun `plugin without version`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val p = plugin("some-plugin", "com.example.plugin")
            val result = generator.generate(emptyMetadata(plugins = mapOf("some-plugin" to p)))

            assertThat(result).contains("some-plugin = { id = \"com.example.plugin\" }")
        }

        @Test
        fun `plugin version ref fallback to inline when alias not in versions`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("not-in-versions", "1.0.0")
            val p = plugin("some-plugin", "com.example.plugin", version = v)
            val result = generator.generate(emptyMetadata(plugins = mapOf("some-plugin" to p)))

            assertThat(result).contains("some-plugin = { id = \"com.example.plugin\", version = \"1.0.0\" }")
            assertThat(result).doesNotContain("version.ref")
        }
    }

    @Nested
    inner class SpecialCharacters {
        @Test
        fun `special characters in version values are escaped`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("special", "1.0.0-\"beta\"")
            val result = generator.generate(emptyMetadata(versions = mapOf("special" to v)))

            assertThat(result).contains("special = \"1.0.0-\\\"beta\\\"\"")
        }

        @Test
        fun `backslash in values is escaped`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("path", "C:\\Users\\lib")
            val result = generator.generate(emptyMetadata(versions = mapOf("path" to v)))

            assertThat(result).contains("path = \"C:\\\\Users\\\\lib\"")
        }

        @Test
        fun `newlines and tabs are escaped`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("multiline", "1.0\n2.0\t3.0")
            val result = generator.generate(emptyMetadata(versions = mapOf("multiline" to v)))

            assertThat(result).contains("multiline = \"1.0\\n2.0\\t3.0\"")
        }
    }

    @Nested
    inner class EmptySectionsOmitted {
        @Test
        fun `empty sections are not included in output`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT.copy(includeComments = false))
            val v = version("kotlin", "2.1.20")
            val result = generator.generate(emptyMetadata(versions = mapOf("kotlin" to v)))

            assertThat(result).contains("[versions]")
            assertThat(result).doesNotContain("[libraries]")
            assertThat(result).doesNotContain("[bundles]")
            assertThat(result).doesNotContain("[plugins]")
        }
    }

    @Nested
    inner class WriteMethod {
        @Test
        fun `writes file to specified path`(@TempDir tempDir: Path) {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val content = "# test content\n"
            generator.write(content, tempDir)

            val file = tempDir.resolve("libs.versions.toml")
            assertThat(file).exists()
            assertThat(file.readText()).isEqualTo(content)
        }

        @Test
        fun `creates parent directories`(@TempDir tempDir: Path) {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val content = "# test\n"
            val nested = tempDir.resolve("a/b/c")
            generator.write(content, nested)

            val file = nested.resolve("libs.versions.toml")
            assertThat(file).exists()
            assertThat(file.readText()).isEqualTo(content)
        }

        @Test
        fun `writes with UTF-8 encoding`(@TempDir tempDir: Path) {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val content = "# Кириллица и спецсимволы: \u00e9\u00e0\u00fc\n"
            generator.write(content, tempDir)

            val file = tempDir.resolve("libs.versions.toml")
            assertThat(file.readText(Charsets.UTF_8)).isEqualTo(content)
        }

        @Test
        fun `overwrites existing file`(@TempDir tempDir: Path) {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val file = tempDir.resolve("libs.versions.toml")
            java.nio.file.Files.writeString(file, "old content")

            generator.write("new content", tempDir)
            assertThat(file.readText()).isEqualTo("new content")
        }

        @Test
        fun `uses config filename`(@TempDir tempDir: Path) {
            val config = TomlConfig.DEFAULT.copy(filename = "custom.toml")
            val generator = TomlGenerator(config)
            generator.write("content", tempDir)

            assertThat(tempDir.resolve("custom.toml")).exists()
            assertThat(tempDir.resolve("libs.versions.toml")).doesNotExist()
        }
    }

    @Nested
    inner class FullEndToEnd {
        @Test
        fun `full metadata end-to-end`() {
            val generator = TomlGenerator(TomlConfig.DEFAULT)

            val kotlinVersion = version("kotlin", "2.1.20")
            val springBootVersion = version("spring-boot", "3.4.0")

            val metadata = emptyMetadata(
                versions = mapOf(
                    "kotlin" to kotlinVersion,
                    "spring-boot" to springBootVersion,
                ),
                libraries = mapOf(
                    "kotlin-stdlib" to library("kotlin-stdlib", "org.jetbrains.kotlin", "kotlin-stdlib", version = kotlinVersion),
                    "kotlin-reflect" to library("kotlin-reflect", "org.jetbrains.kotlin", "kotlin-reflect", version = kotlinVersion),
                    "spring-boot-starter" to library(
                        alias = "spring-boot-starter",
                        group = "org.springframework.boot",
                        artifact = "spring-boot-starter",
                        version = springBootVersion,
                        isDeprecated = true,
                        deprecation = DeprecationInfo(
                            message = "Legacy starter",
                            replacedBy = "spring-boot-starter-web",
                            since = "3.0",
                            removalVersion = "4.0",
                        ),
                    ),
                    "spring-boot-starter-web" to library(
                        "spring-boot-starter-web",
                        "org.springframework.boot",
                        "spring-boot-starter-web",
                        version = springBootVersion
                    ),
                ),
                bundles = mapOf(
                    "kotlin" to bundle("kotlin", listOf("kotlin-stdlib", "kotlin-reflect")),
                ),
                plugins = mapOf(
                    "kotlin-jvm" to plugin("kotlin-jvm", "org.jetbrains.kotlin.jvm", version = kotlinVersion),
                ),
            )

            val result = generator.generate(metadata)

            assertThat(result).isEqualTo(
                """
                |# Generated by Dependanger (toml-version-catalog)
                |
                |[versions]
                |kotlin = "2.1.20"
                |spring-boot = "3.4.0"
                |
                |[libraries]
                |kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
                |kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
                |# DEPRECATED: Legacy starter. Use spring-boot-starter-web instead. Removal: 4.0.
                |spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
                |spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
                |
                |[bundles]
                |kotlin = ["kotlin-stdlib", "kotlin-reflect"]
                |
                |[plugins]
                |kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
                |""".trimMargin()
            )
        }

        @Test
        fun `generate and write round trip`(@TempDir tempDir: Path) {
            val generator = TomlGenerator(TomlConfig.DEFAULT)
            val v = version("kotlin", "2.1.20")
            val lib = library("kotlin-stdlib", "org.jetbrains.kotlin", "kotlin-stdlib", version = v)
            val metadata = emptyMetadata(
                versions = mapOf("kotlin" to v),
                libraries = mapOf("kotlin-stdlib" to lib),
            )

            val toml = generator.generate(metadata)
            generator.write(toml, tempDir)

            val file = tempDir.resolve("libs.versions.toml")
            assertThat(file).exists()
            assertThat(file.readText()).isEqualTo(toml)
        }
    }
}
