package io.github.zenhelix.dependanger.features.report.renderer

import io.github.zenhelix.dependanger.features.report.model.ReportData
import org.commonmark.parser.Parser
import org.commonmark.renderer.html.HtmlRenderer

internal class HtmlReportRenderer(
    private val markdownRenderer: MarkdownReportRenderer,
) : ReportRenderer {

    private val mdParser: Parser = Parser.builder().build()
    private val htmlRenderer: HtmlRenderer = HtmlRenderer.builder().build()

    override fun render(data: ReportData): String {
        val markdown = markdownRenderer.render(data)
        val document = mdParser.parse(markdown)
        val body = htmlRenderer.render(document)
        return htmlTemplate(generatedAt = data.generatedAt, body = body)
    }

    private fun htmlTemplate(generatedAt: String, body: String): String = """
        |<!DOCTYPE html>
        |<html lang="en">
        |<head>
        |<meta charset="utf-8">
        |<meta name="viewport" content="width=device-width, initial-scale=1">
        |<title>Dependanger Report</title>
        |<style>
        |  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
        |         max-width: 960px; margin: 0 auto; padding: 24px; color: #333; line-height: 1.5; }
        |  h1 { border-bottom: 2px solid #2196F3; padding-bottom: 8px; }
        |  h2 { border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 32px; }
        |  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
        |  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        |  th { background: #f5f5f5; font-weight: 600; }
        |  tr:hover { background: #fafafa; }
        |  code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
        |  footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd;
        |           font-size: 0.85em; color: #888; }
        |</style>
        |</head>
        |<body>
        |$body
        |<footer>Generated by Dependanger at $generatedAt</footer>
        |</body>
        |</html>
    """.trimMargin()
}
